### ISSUE TITLE
Can't import MessageActivityData from discord_typings

### ISSUE THREAD

**Issue by EmmmaTech** [Bluenix2/discord-typings#10]
Hello, so I'm not sure what's going on, but whenever I try to import MessageActivityData from discord_typings, I get this import error:
```
ImportError: cannot import name 'MessageActivityData' from 'discord_typings' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord_typings/__init__.py)
```

**Comment by Bluenix2** [comment]
Hi! Thank you for opening this issue.

Unfortunately (or rather, fortunately) this has already been fixed in 6922da7703ff29976f529cb7af9ea8f09c92df0d, but that is not yet released.

Current plans before another release (0.5.0) are just to merge in the [gateway events rework](https://github.com/Bluenix2/discord-typings/tree/gateway-events). I was considering including a similar audit log rework in this release but that is still pending because it has not been begun.

The blocker for the gateway events to be merged is a release from `typing_extensions` to support generic typed dicts.
